import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 24,
    marginBottom: 24,
    color: "#111827",
  },
  list: {
    paddingBottom: 32,
  },
  emptyText: {
    textAlign: "center",
    marginTop: 40,
    color: "#6B7280",
    fontSize: 16,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  name: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  pointsCount: {
    fontSize: 14,
    color: "#9CA3AF",
  },
  description: {
    fontSize: 15,
    color: "#4B5563",
    marginTop: 6,
  },
  detailButton: {
    marginTop: 14,
    backgroundColor: "#FF6F61",
    paddingVertical: 14,
    borderRadius: 30,
    alignItems: "center",
    shadowColor: "#FF6F61",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  detailButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: "auto",
    marginBottom: 24,
    gap: 12,
  },
  footerButton: {
    flex: 1,
    width: 100,
    backgroundColor: "#F3E8EE",
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: "center",
    shadowColor: "#FF6F61",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  footerButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FF6F61",
  },
  logoutButton: {
    backgroundColor: "#EF4444",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 30,
    justifyContent: "center",
    shadowColor: "#EF4444",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
});